// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { 
        type: "autogenerated", 
        dirName: "." 
    },
    {
        type: 'link',
        label: 'Mercury Workshop Homepage',
        href: 'https://mercurywork.shop/',
    },
],
};

module.exports = sidebars;
