on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest
      
      - name: build
        run: |
          pnpm i
          npx astro build
          sudo npm i -g wrangler

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=tn-oxide-docs